services:
  postgres:
    # ./postgres/Dockerfile 생성 필요
    build: ../postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME:-shin}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-}"
      POSTGRES_DB: "${DB_NAME:-}"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.9.1
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://${KAFKA_HOST:-localhost}:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  payments:
    image: havegrit/driply-payments:${IMAGE_TAG:-latest}
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-driply_dev}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME:-shin}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD:-}"
    volumes:
      - payment_data:/app/data

  nginx:
    image: nginx:1.28.0
    container_name: nginx
    restart: always
    volumes:
      - ../reverse_proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../reverse_proxy/nginx/conf.d:/etc/nginx/conf.d
      - ../reverse_proxy/html:/usr/share/nginx/html
      - ../reverse_proxy/certbot/www:/var/www/certbot
      - ../reverse_proxy/certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../reverse_proxy/certbot/www:/var/www/certbot
      - ../reverse_proxy/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"

volumes:
  postgres_data:
  kafka_data:
  payment_data:

networks:
  default:
    name: payments-network
    external: true