spring:
  application:
    name: payments
  profiles:
    active: dev
    include: secret
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: payment-callback
          contentType: application/json