app:
  domain:
    name: driply-coffee.shop
    base-url: https://driply-coffee.shop
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: payments
  profiles:
    active: ${PROFILE}
    include: secret
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  cloud:
    stream:
      binders:
        kafka-binder:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: ${KAFKA_HOST:localhost}:9092
      bindings:
        consumer-in-0:
          destination: payment-callback
          group: payment-callback-group
          binder: kafka-binder
          contentType: application/json
        producer-out-0:
          destination: payment-callback
          binder: kafka-binder
          contentType: application/json
security:
  protected:
    paths:
      - /api/v1/payment/callback
  proxy:
    hosts:
      - nginx